/**
 * SEMPela - Mock Data Layer
 * Simulates database records with real Cloudinary-hosted sample videos.
 * In production, replace with real API calls to your Next.js backend.
 * Author: Josué Sempela
 */

import { Video } from '../store/useVideoStore';

// Sample short videos from public sources
export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Ndombolo à Kinshasa 💃',
    description: "Ambiance dans une ruelle de Kinshasa — ndombolo, sourires et pas endiablés. #ndombolo #kinshasa #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400',
    likes: 34210,
    views: 210345,
    duration: 28,
    tags: ['ndombolo', 'kinshasa', 'congo'],
    username: '@ndombolo_star',
    userAvatar: 'https://i.pravatar.cc/150?img=45',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: '2',
    title: 'Marche du marché central 🥭',
    description: "Couleurs et saveurs du marché central — vendeuses, épices et mangues fraîches. #marché #kinshasa #afrique",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=400',
    likes: 12890,
    views: 98765,
    duration: 40,
    tags: ['marché', 'food', 'kinshasa'],
    username: '@vendeuse_congo',
    userAvatar: 'https://i.pravatar.cc/150?img=46',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: '3',
    title: 'Tambours traditionnels 🥁',
    description: "Rythmes congolais traditionnels — percussions et danse collective. #tambour #tradition #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508587880373-9b6f1d9e9b5e?w=400',
    likes: 45210,
    views: 340120,
    duration: 22,
    tags: ['percussions', 'tradition', 'danse'],
    username: '@batteur_du_congo',
    userAvatar: 'https://i.pravatar.cc/150?img=47',
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: '4',
    title: 'Congo River Sunset 🚤',
    description: "Balade sur le fleuve Congo au coucher du soleil — paysages majestueux. #congoriver #nature #afrique",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400',
    likes: 18932,
    views: 120890,
    duration: 60,
    tags: ['congoriver', 'nature', 'sunset'],
    username: '@passeur_du_fleuve',
    userAvatar: 'https://i.pravatar.cc/150?img=48',
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: '5',
    title: 'Cuisine de rue : brochettes et saka saka 🍢',
    description: "Recette et préparation rapides des brochettes congolaises et du saka-saka. #cuisine #streetfood #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    likes: 41245,
    views: 256400,
    duration: 35,
    tags: ['food', 'congo', 'streetfood'],
    username: '@chef_de_rue',
    userAvatar: 'https://i.pravatar.cc/150?img=49',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: '6',
    title: 'Mode: wax et tenues traditionnelles 👗',
    description: "Défilé improvisé — tissus wax, couleurs et style congolais. #mode #wax #afrique",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    likes: 17654,
    views: 98012,
    duration: 24,
    tags: ['mode', 'wax', 'congo'],
    username: '@styliste_kin',
    userAvatar: 'https://i.pravatar.cc/150?img=50',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: '7',
    title: 'Danses de rue: Congo moves ✨',
    description: "Compilation de pas de danse dans les rues — énergie et bonne humeur. #danse #streetdance #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
    likes: 25678,
    views: 214300,
    duration: 30,
    tags: ['dance', 'kinshasa', 'viral'],
    username: '@crew_kinshasa',
    userAvatar: 'https://i.pravatar.cc/150?img=51',
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    id: '8',
    title: 'Faune et forêt tropicale 🌿',
    description: "Regards sur la biodiversité – forêts humides et animaux d'Afrique centrale. #faune #forêt #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400',
    likes: 62100,
    views: 412000,
    duration: 45,
    tags: ['wildlife', 'forest', 'congo'],
    username: '@naturaliste_bc',
    userAvatar: 'https://i.pravatar.cc/150?img=52',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: '9',
    title: 'Street Comedy — Kinshasa 😂',
    description: "Sketch humoristique dans la rue — petites scènes du quotidien. #comedy #kinshasa #afrique",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=400',
    likes: 89234,
    views: 678500,
    duration: 18,
    tags: ['comedy', 'street', 'viral'],
    username: '@humoriste_kin',
    userAvatar: 'https://i.pravatar.cc/150?img=53',
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
  {
    id: '10',
    title: 'Portrait: artisan sculpteur 🪚',
    description: "Rencontre avec un artisan sculpteur local — savoir-faire et tradition. #artisanat #sculpture #congo",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1475178625426-7c4a9f7d9f55?w=400',
    likes: 156000,
    views: 1201000,
    duration: 50,
    tags: ['artisanat', 'portrait', 'congo'],
    username: '@artisan_du_coin',
    userAvatar: 'https://i.pravatar.cc/150?img=54',
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
  },
];

// Admin password (in production, use proper auth)
export const ADMIN_PASSWORD = 'sempela2024';
